export const SET_SEARCH_FIELD = "SET_SEARCH_FIELD";
export const SET_ITEMS = "SET_ITEMS";
export const SET_ITEM = "SET_ITEM";
export const CLEAR_SEARCH_FIELD = "CLEAR_SEARCH_FIELD";
export const CLEAR_ITEMS = "CLEAR_ITEMS";
export const SET_CATEGORIES = "SET_CATEGORIES";